meroxa/turbine-core

- pkg/ir/schema.go
- pkg/ir/spec.go
- pkg/ir/spec_test.go
This is so it can be used by the CLI.
Part of https://github.com/meroxa/product/issues/589.
> feat: ValidateVersion separately

- pkg/ir/schema.json
- pkg/ir/schema_test.go
Spec was not actually being validation in API, and has changed since the initial validation changes. We want to bring them up to date https://github.com/meroxa/platform-api/pull/1469
> Fix ir spec validation

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
**Before**
```
pr = TurbineCore::Process.new(
^^^^^^^^^
from /Users/rb/code/meroxa/turbine-examples/ruby/simple/app.rb:18:in `call'
from /Users/rb/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbine_rb-0.1.0/lib/turbine_rb.rb:52:in `run'
from -e:1:in `<main>'
exit status 1
Error: exit status 1
```
```
Unknown field name 'collection' in initialization map entry. (ArgumentError)
from /Users/rb/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbine_rb-0.1.0/lib/turbine_rb/client.rb:60:in `new'
from /Users/rb/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbine_rb-0.1.0/lib/turbine_rb/client.rb:60:in `write'
from /Users/rb/code/meroxa/turbine-examples/ruby/simple/app.rb:19:in `call'
from /Users/rb/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbine_rb-0.1.0/lib/turbine_ …
```
> fix: latest core changes for rb

- .github/workflows/pull_request.yml
- Makefile
Adds ruby tests after go tests in the github runner.
Check out the action and see the turbine rb dependency install + successful test run
> ci: add ruby specs to GitHub action

- lib/ruby/turbine_rb/lib/turbine_rb.rb
Fixes references for the server after refactoring the init function
> fix(turbine_rb): correct server references

- lib/ruby/turbine_rb/lib/templates/app/app.rb
- lib/ruby/turbine_rb/lib/turbine_rb.rb
- lib/ruby/turbine_rb/lib/turbine_rb/records.rb
- lib/ruby/turbine_rb/spec/turbine_rb_records_spec.rb
- lib/ruby/turbine_rb/turbine_rb.gemspec
+ Modeled after how we expose a record interface in other turbine libs
+ Adds `.get` and `.set` methods to record object to allow reading/writing values (Can be dot separated) 
+ Adds `.unwrap!` to record object for unwrapping CDC payloads
+ Allows user to return `Records` object or Array of Record objects in their function
Using:
```
class Masker < TurbineRb::Process
def call(records:)
records.each do |r|
r.set("customer_email", "MASKED")
end
records
end
end
```
Result:
> feat: Add Record wrappers for working w records

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/lib/turbine_rb/records.rb
+ Fixes client `process` method to wrap records with Records interface
+ `get` and `set` now appropriately handle freeform json data + a little refactoring
DEMO:
Associated function:
```
class Masker < TurbineRb::Process # might be useful to signal that this is a special Turbine call
def call(records:)
puts "got records: #{records}"
records.map { |r| r.set('message', "byeeeeee") }
records
end
end
```
With simple ruby app fixture data
> fix(turbine_rb): add record interface to local run

- lib/ruby/turbine_rb/CHANGELOG.md
- lib/ruby/turbine_rb/lib/turbine_rb/records.rb
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
- lib/ruby/turbine_rb/spec/turbine_rb/record_spec.rb
Correct rb to only set schema fields when we detect json schema format
> fix: set new keys on unformatted json

- .github/workflows/release_ruby.yml
- lib/ruby/turbine_rb/Gemfile
- lib/ruby/turbine_rb/Gemfile.lock
+ Added `MEROXA_MACHINE` github machine user token to repo
+ Made sure @meroxa/automation has access to repo
+ Added `RUBYGEMS_AUTH_TOKEN` token to repo
+ Created github action that will detect version changes and publish to ruby gems + tag
+ Create a PR with a version bump using `bump patch|minor|major` locally OR manually increment the version (discouraged)
+ Add changelog entry(s) to CHANGELOG.md
+ Get PR approval / merge
+ Gem with a bumped version is automatically published to rubygems
+ Commit is tagged with bumped version
> ci: add automated ruby gem release

- .github/workflows/release_ruby.yml
`with` can only be used with `uses`, so we use `env` like in the previous step
> ci: fix keyword for env vars

- .github/workflows/release_ruby.yml
Adds a guard so that we only tag when publishing a gem
> ci: add guard for rb tagging

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/spec/turbine_rb/client_spec.rb
This should fix the issue experienced in the acceptance tests 
```
=== RUN   TestAppMgmt/RB:_Deploy_app
turbine_test.go:432: /app/bin/meroxa --cli-config-file /root/meroxa.main.env app deploy --path /apps/turbine_rb/tmp/app/rb-acceptance-app-864f01c9-fe73-4e85-8ba1-535f92df0f0b --spec 0.1.1 --json
turbine_test.go:432: 	✔ Checked your language is "ruby"
✔ Checked your application name is "rb-acceptance-app-864f01c9-fe73-4e85-8ba1-535f92df0f0b"
/usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.1/lib/turbine_rb/client.rb:123:in `method_missing': undefined method `to_a' for <TurbineCore::Collection: name: "", stream: "", records: []>:TurbineCore::Collection (NoMethodError)
records: pb_collection.to_a,
^^^^^
Did you mean?  to_h
to_s
from …
```
> turbine-rb: fix collection wrapping/unwrapping

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
Another error
```
/usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.2/lib/turbine_rb/client.rb:121:in `initialize': Expected array as initializer value for repeated field 'records' (given TurbineCore::Collection). (ArgumentError)
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.2/lib/turbine_rb/client.rb:121:in `new'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.2/lib/turbine_rb/client.rb:121:in `unwrap'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.2/lib/turbine_rb/client.rb:78:in `write'
from /apps/turbine_rb/tmp/app/rb-acceptance-app-1d0e52a8-7399-4a8b-8113-cbdc12b7c9d5/app.rb:19:in `call'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.2/lib/turbine_rb.rb:52:in `record'
from -e:1:in `<main>'
```
> turbine-rb: ensure records is an array

- lib/ruby/turbine_rb/Gemfile.lock
- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
- pkg/ir/spec.go
- pkg/ir/spec_test.go
/usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.3/lib/turbine_rb/client.rb:127:in `initialize': Invalid type TurbineCore::Collection to assign to submessage field 'records'. (Google::Protobuf::TypeError)
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.3/lib/turbine_rb/client.rb:127:in `new'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.3/lib/turbine_rb/client.rb:127:in `unwrap'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.3/lib/turbine_rb/client.rb:78:in `write'
from /apps/turbine_rb/tmp/app/rb-acceptance-app-38359f2a-8746-45ed-83e2-11e0a4085b6c/app.rb:19:in `call'
from /usr/local/lib/ruby/gems/3.1.0/gems/turbine_rb-0.2.3/lib/turbine_rb.rb:52:in `record'
from -e:1:in `<main>'
exit status 1
> turbine-rb: fix bug, process_call should be returning records

- Makefile
- pkg/ir/spec_test.go
- pkg/server/record.go
- pkg/server/record_test.go
Stop copying the dag lock around when using the spec.
Add vet check.
> turbine-core golang: Use ptr to avoid copying the mutex lock

- lib/ruby/turbine_rb/README.md
- pkg/app/config.go
- pkg/app/config_test.go
- pkg/app/templates/ruby/app.json
- pkg/server/run_test.go
Remove `environment` variable from app config and add note about deprecation.
Fixes #82
> Deprecate `environment` from app config

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yml
Keep up to date automatically as long as dependency updates don't break anything
Related to https://github.com/meroxa/engineering/issues/51
|||
> Automerge Dependabot PRs with passing automation

- Makefile
- pkg/app/config.go
- pkg/app/config_test.go
- pkg/app/init.go
- pkg/ir/schema.go
- pkg/ir/spec.go
- pkg/ir/spec_test.go
- pkg/server/record.go
- pkg/server/record_test.go
- pkg/server/run.go
- pkg/server/run_test.go
- pkg/server/server.go
Small refactor in the record service to make use of the validation rules in the proto.
Rename the `record` to be `spec builder` instead, more clarity.
Part of https://github.com/meroxa/turbine-core/issues/107
|||
> Refactor record service; rename to spec builder

- pkg/ir/schema.json
- pkg/ir/schema_test.go
Updates the enum's to use the language strings defined by the turbine proto.
> Update language validation strings

- pkg/ir/schema.json
- pkg/ir/schema_test.go
Oh boy, how much time do you have? 
See https://meroxa.slack.com/archives/C03F15EKFU3/p1682697464659729
Adding back shorthand names, since we rely on them for older specs.
Changed 1 of 2 python tests to use the shorthand
> fix: add back shorthand validations

- pkg/app/init.go
Some fun context:
https://github.com/golang/go/issues/44305
> You should use path.Join, not filepath.Join for embed filenames.
.... so `filepath` must be using the back slashes, but somehow embedded paths are always forward slashes even on windows 😵‍💫
> fix windows embedded templates

- pkg/app/templates/python/main.py
- pkg/app/templates/python/requirements.txt
While we wait to ship IR, the apps initialized with turbine-core in python do not match the deploy and run
> fix: update turbine-py for non IR

- pkg/app/init.go
- pkg/app/init_test.go
https://pkg.go.dev/embed
Added the tag to ensure that dotfiles in subdirectories would be included.
> fix: ensure embedded subdirectory dotfiles are included

- pkg/ir/schema.json
- pkg/ir/schema_test.go
The connector count/type validation logic is being moved to the libraries that are generating the IR spec. 
This removes the following requirements:
- Only one source connector is allowed
- At least one connector of any type is required 
Fixes https://github.com/meroxa/product/issues/899
|||
> [Stateful Stream Processing] Remove connector count validations

- pkg/ir/spec.go
- pkg/ir/spec_test.go
Relaxes root validation for sources. In addition this change also removes `ValidateDAG()` from the `BuildDAG()` function. It is now intended for callers to invoke both `ValidateDAG()` and `BuildDAG()` independently 
Fixes https://github.com/meroxa/product/issues/902
|||
> [Stateful Stream Processing] Relax Root Number Validation in IR

- pkg/server/run.go
- pkg/server/run_test.go
Improves an error message around missing resource names in the fixtures section of `app.json`.
Fixes https://github.com/meroxa/product/issues/954
```bash
~/go/src/notion-s3 main
❯ meroxa apps run --debug
2023/08/02 16:34:52 rpc error: code = Unknown desc = read /Users/samir/go/src/notion-s3: is a directory
Error: exit status 1
```
```bash
~/go/src/notion-s3 main
❯ ../cli/meroxa apps run --debug
Error: 2023/08/03 13:12:13 rpc error: code = InvalidArgument desc = No fixture file found for resource notion. Ensure that the resource is declared in your app.json.
exit status 1
```
> Better error message for missing resource in app.json

- pkg/app/init.go
- pkg/app/init_test.go
This is an improvement over what we had which will be needed to recursively clone a template with different subdirectories (will be needed for Java)
> feat: recursive apps init
