meroxa/turbine-core

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/spec/turbine_rb_client_spec.rb
Allows passing configs using ruby hashes as the third argument to `.records` and `.write`
> feat(turbine_rb): pass config via ruby hash arg

- lib/ruby/turbine_rb/bin/turbine-function
- lib/ruby/turbine_rb/lib/turbine_rb.rb
+ Adds gRPC health check using https://github.com/grpc/grpc/blob/master/src/ruby/pb/grpc/health/checker.rb
+ Fixes function executable to use pwd as data app path
> Add gRPC health check and fix function executable

- lib/ruby/turbine_rb/CHANGELOG.md
- lib/ruby/turbine_rb/lib/templates/Dockerfile
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
🤦  Fixes a mi-🥩 with Dockerfile entrypoint cmd
> fix(turbine_rb): dockerfile entrypoint

- lib/ruby/turbine_rb/CHANGELOG.md
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
- lib/ruby/turbine_rb/spec/turbine_rb/client_spec.rb
+ Add spec follow up for #51 
+ Refactors an older spec to better assert method being called
> Bump to 0.1.2 with better test coverage

- lib/ruby/turbine_rb/.rubocop.yml
- lib/ruby/turbine_rb/Gemfile.lock
- lib/ruby/turbine_rb/lib/turbine_rb.rb
- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
- lib/ruby/turbine_rb/spec/turbine_rb/client_spec.rb
Includes minor formatting and refactoring.
Fixes #58
> Pass collection when adding processes

- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
> turbine-rb: bump version

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
- pkg/ir/schema.json
```
database = app.resource(name: "pg")
records = database.records(collection: "sequences")
processed_records = app.process(records: records, process: Passthrough.new)
database.write(records: processed_records, collection: "testing1_fn_rb")
database.write(records: records, collection: "testing1_no_fn_rb")
```
```
meroxa apps run
+------------------------------------------------+
| Destination pg/testing1_no_fn_rb               |
+-----------------+------------------------------+
|           INDEX | RECORD                       |
+-----------------+------------------------------+
|               0 | {"id":1,"message":"goodbye"} |
+-----------------+------------------------------+
| RECORDS WRITTEN | 1                            |
+-----------------+------------------------------+ …
```
> Fix bug that overwrites records

- lib/ruby/turbine_rb/lib/turbine_rb/client.rb
Address comments in: https://github.com/meroxa/turbine-core/pull/73
> Fix typo newrcords -> new_records

- lib/ruby/turbine_rb/lib/turbine_rb/version.rb
> Release v0.2.5

- README.md
> docs: add info how to release rubygem

- lib/ruby/turbine_rb/README.md
Mention bundle for setup and fix a link
Fixes <GitHub Issue>
|||
> Ruby documentation tweaks

- pkg/app/config.go
- pkg/app/init.go
- pkg/app/init_test.go
- pkg/ir/spec.go
- pkg/ir/spec_test.go
- pkg/server/record_test.go
- pkg/server/run_test.go
Fixes https://github.com/meroxa/turbine-core/issues/109
- Utilize these in the CLI and remove the other defined there.
> refactor: utilize lang const

- pkg/app/init_test.go
- pkg/app/templates/javascript/.gitignore
- pkg/app/templates/javascript/README.md
- pkg/app/templates/javascript/app.json
- pkg/app/templates/javascript/fixtures/demo-cdc.json
- pkg/app/templates/javascript/fixtures/demo-no-cdc.json
- pkg/app/templates/javascript/index.js
- pkg/app/templates/javascript/index.test.js
- pkg/app/templates/javascript/package.json
Fixes https://github.com/meroxa/turbine-js/issues/281
> feat: add js templates to turbine-core

- pkg/server/server.go
This allows for the address port to be customized.
|||
> Add run with address for server

- pkg/server/mock/server_mock.go
- pkg/server/server.go
> Add missing interface method; check

- pkg/app/templates/python/main.py
- pkg/app/templates/python/requirements.txt
Editing turbine-py template to use correct imports in the app template and all the requirements to install. \
Fixes <GitHub Issue>
> Edit turbine-py template to use correct imports

- pkg/app/templates/python/requirements.txt
Makes sure our templates have the latest dependencies
> fix: update to python 1.8.2 fix

- pkg/app/templates/python/main.py
- pkg/app/templates/python/requirements.txt
Reverting the template needed for core changes back.
> fix: python template changes to turbine-core

- pkg/app/config.go
- pkg/server/run_test.go
In case we want to run the tests against multiple OSs, changing those too. 
Related to https://github.com/meroxa/product/issues/815
|||
> Form file paths in an OS agnostic way

- pkg/app/templates/ruby/app.rb
> fix: ruby template small nit fix

- lib/ruby/turbine_rb/.github/workflows/main.yml
Upgrade checkout action
Related  to https://github.com/meroxa/product/issues/595
|||
> Upgrade checkout action to v3

- pkg/server/run.go
[📺 Demo](https://meroxa.slack.com/archives/C060WBL2U2V/p1701952302459289)
> fix: process records
